# Generated by Django 5.2.15 on 2026-09-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0021_patient_project_required'),
        ('common', '0052_delete_dicom_catalog'),
        ('laparoscopy', '0013_patient_project_required'),
        ('maxillo', '0031_classification_unique_per_classifier'),
        ('urology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='urology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='urology.patient'),
        ),
        migrations.AddField(
            model_name='fileregistry',
            name='urology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='urology.voicecaption'),
        ),
        migrations.AddField(
            model_name='job',
            name='urology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='urology.patient'),
        ),
        migrations.AddField(
            model_name='job',
            name='urology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='urology.voicecaption'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='urology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='urology.patient'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='urology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='urology.voicecaption'),
        ),
        migrations.AlterField(
            model_name='annotationmethod',
            name='domain',
            field=models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='', help_text='Leave blank for a method available in every domain.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileregistry',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='modality',
            name='domain',
            field=models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='', help_text='Leave blank for a modality available in every domain.', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='maxillo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['domain', 'file_type', 'urology_patient'], name='maxillo_fil_domain_4a1020_idx'),
        ),
    ]
