# Generated by Django 5.2.15 on 2026-09-08 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0052_delete_dicom_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrologyProject',
            fields=[
            ],
            options={
                'verbose_name': 'Urology project',
                'verbose_name_plural': 'Urology projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urology_datasets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urology_dataset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Expose this folder (and its patients) in the anonymous public demo at /demo/<domain>/. Only anonymized or synthetic studies may be flagged.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urology_folders_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='urology.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urology_folders', to='common.project')),
            ],
            options={
                'db_table': 'urology_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('project_manager', 'Project Manager')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='urology.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urology_folder_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urology_folder_access',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'urology_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='urology_tag_name_c501c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='urology.dataset')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='urology.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='urology_patients', to='common.modality')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urology_patients', to='common.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urology_patients_uploaded', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='patients', to='urology.tag')),
            ],
            options={
                'db_table': 'urology_patient',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(blank=True, default='', max_length=255)),
                ('text_caption', models.TextField(blank=True, null=True)),
                ('original_text_caption', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='urology.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urology_voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urology_voicecaption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Share link expiry; null = never expires', null=True)),
                ('query_params', models.JSONField(default=dict)),
                ('query_summary', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('patient_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Any logged-in user'), ('public', 'Anyone with link')], default='private', max_length=20)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urology_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urology_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='urology_exp_user_id_58d69d_idx'), models.Index(fields=['status', 'created_at'], name='urology_exp_status_4cdfc6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project'], name='urology_fol_project_d63dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='urology_fol_parent__d7ae8e_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='urology_fol_name_64fa45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder'], name='urology_fol_folder__efeed5_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user'], name='urology_fol_user_id_4e9cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['role'], name='urology_fol_role_833d68_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder', 'role'], name='urology_fol_folder__c5f4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user', 'role'], name='urology_fol_user_id_29b38f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderaccess',
            unique_together={('user', 'folder')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='urology_pat_visibil_514b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='urology_pat_uploade_18322c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='urology_pat_folder__16d772_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project'], name='urology_pat_project_61e7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='urology_pat_name_fa11e5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='urology_pat_visibil_266800_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='urology_voi_patient_8040f1_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='urology_voi_process_0dc98c_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='urology_voi_user_id_67a9a9_idx'),
        ),
    ]
