# Generated by Django 5.2.15 on 2026-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_drop_dicom_resource_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationset',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], default='maxillo', max_length=20),
        ),
    ]
