# Generated by Django 5.2.15 on 2026-09-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_alter_annotationset_domain'),
        ('brain', '0021_patient_project_required'),
        ('common', '0053_fileregistry_urology_patient_and_more'),
        ('laparoscopy', '0013_patient_project_required'),
        ('maxillo', '0031_classification_unique_per_classifier'),
        ('urology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationset',
            name='urology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='urology.patient'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['urology_patient', 'kind'], name='annotations_urology_247a9e_idx'),
        ),
    ]
